In [2]:
import pandas as pd

In [3]:
pd.read_csv('./gsrf.csv')

            Id  WnvPresent
0            1           0
1            2           0
2            3           0
3            4           0
4            5           0
5            6           0
6            7           0
7            8           0
8            9           0
9           10           0
10          11           0
11          12           0
12          13           0
13          14           0
14          15           0
15          16           0
16          17           0
17          18           0
18          19           0
19          20           0
20          21           0
21          22           0
22          23           0
23          24           0
24          25           0
25          26           0
26          27           0
27          28           0
28          29           0
29          30           0
...        ...         ...
116263  116264           1
116264  116265           1
116265  116266           1
116266  116267           1
116267  116268           1
116268  116269           1
116269  116270           1
116270  116271           1
116271  116272           1
116272  116273           1
116273  116274           1
116274  116275           1
116275  116276           1
116276  116277           1
116277  116278           1
116278  116279           1
116279  116280           1
116280  116281           1
116281  116282           1
116282  116283           1
116283  116284           1
116284  116285           1
116285  116286           1
116286  116287           1
116287  116288           1
116288  116289           1
116289  116290           1
116290  116291           1
116291  116292           1
116292  116293           1

[116293 rows x 2 columns]